---
title: "Exercise 1.2.3"
---

## Problem

Decide which of the following represent true statements about the nature of sets.
For any that are false, provide a specific example where the statement in question does not hold.

(a) If $A_1 \supseteq A_2 \supseteq A_3 \supseteq A_4 \cdots$ are all sets containing an infinite number of elements, then the intersection $\bigcap^{\infty}_{n=1}A_n$ is infinite as well.
(b) If $A_1 \supseteq A_2 \supseteq A_3 \supseteq A_4 \cdots$ are all finite, nonempty sets of real numbers, then the intersection $\bigcap^{\infty}_{n=1}A_n$ is finite and nonempty.
(c) $A \cap (B \cup C) = (A \cap B) \cup C$
(d) $A \cap (B \cap C) = (A \cap B) \cap C$
(e) $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$

## Solution

### (a)

Let us reuse Example 1.2.2 for this exercise.
It also helps to review the argument used in the example, which is not entirely trivial in my opinion, if I say so myself.

::: {#lem-order}
Let $n \in \mathbb{N}$ and $A_n = \{m \in \mathbb{N} : m \geq n\}$. Then, $\bigcap^{\infty}_{n=1}A_n = \emptyset$.

::: {.proof}
Let $A = \bigcap^{\infty}_{n=1}A_n$. For the sake of contradiction, suppose that $A \not = \emptyset$.
Since $A \subseteq \mathbb{N}$, let $N \in \mathbb{N}$ and suppose that $N \in A$.
It then follows from the definition of infinite intersection that $N \in A_n$ for all $n \in \mathbb{N}$.
However, we see that $N \in A_N$ but $N \not \in A_{N+1}$ by the definition of $A_n$.
Therefore, it is not the case that $N \in A_n$ for all $n \in \mathbb{N}$, thus $N \not \in A$, and this is a contradiction.
It follows that no such $N \in \mathbb{N}$ exists and we have that $A = \emptyset$ as desired.
:::
:::

With Lemma 1, it follows that (a) is a *false* statement.

### (b)
In order to help us with the argument, we will have to rely on some outside ideas.
The Well-ordering Principle states that any nonempty subsets of the natural numbers must contain a minimum.

::: {.lemma}
**Well-ordering Principle** Let $S \subseteq \mathbb{N}$ with $S \not = \emptyset$.
Then, there exists $m \in S$ such that $m \leq s$ for all $s \in S$.
:::

Let us prove a lemma that specifies the conditions for (b) to be a true statement.
Intuitively, the smallest nonempty subset in the sequence of nested subsets must be the intersection.
We begin the argument by asserting the existence of such a minimal subset.

::: {#lem-order}
Let $A_1, A_2, \ldots$ be finite, nonempty sets of real numbers such that $A_i \supseteq A_j$ whenever $i \leq j$ for all $i, j \in \mathbb{N}$.
Then, there exists $m \in \mathbb{N}$ such that $|A_m| \leq |A_n|$ for all $n \in \mathbb{N}$.

::: {.proof}
Let $S = \{|A_n| : n \in \mathbb{N}\}$.
Since $A_1$ is finite and nonempty, it follows that $|A_1| \in S$, thus $S \not = \emptyset$ and $S \subseteq \mathbb{N}$.
By the the Well-ordering principle that there exists $k \in S$ with $k \leq |A_n|$ for all $n \in \mathbb{N}$. 
Since $k \in S$, there exists $m \in \mathbb{N}$ such that $k = |A_m|$.
:::
:::

Now we show that this smallest subset $A_m$ indeed is the intersection of the nested subsets. Furthermore, recall that for sets $A$ and $B$, $A = B$ if and only if $A \subseteq B$ and $A \supseteq B$. 

::: {#lem-order}
Let $A_1, A_2, \ldots$ be finite, nonempty sets of real numbers such that $A_i \supseteq A_j$ whenever $i \leq j$ for all $i, j \in \mathbb{N}$.
Then, there exists $m \in \mathbb{N}$ such that $\bigcap_{n=1}^{\infty}A_n = A_m$.

::: {.proof}
From lemma 2, there exists $m \in \mathbb{N}$ such that $|A_m| \leq |A_n|$ for all $n \in \mathbb{N}$.
Let $a \in \bigcap_{n=1}^{\infty}A_n$.
It follows that $a \in A_n$ for all $n \in \mathbb{N}$, thus $a \in A_m$ as well, and we have that $\bigcap_{n=1}^{\infty}A_n \subseteq A_m$. 
Now, let $a \in A_m$ and let $i \in \mathbb{N}$. There are two cases to consider:

- Suppose that $i \leq m$.
By the definition of $A_n$, it follows that $A_i \supseteq A_m$, hence $a \in A_i$. 
- Suppose that $i > m$.
It also follows from the definition that $A_m \supseteq A_i$ and it immediately follows that $|A_m| \geq |A_i|$.
Lemma 2 implies that $|A_m| \leq |A_i|$, thus it must be the case that $|A_m| = |A_i|$.
Since a proper subset of a finite set has smaller cardinality, it follows that $A_m = A_i$, thus we have that $a \in A_i$.

In either case, we have that $a \in A_i$, so by the definition of infinite intersection, it follows that $a \in \bigcap_{n=1}^{\infty}A_n$, and thus $A_m \subseteq \bigcap_{n=1}^{\infty}A_n$.
With inclusion in both directions, we conclude that $\bigcap_{n=1}^{\infty}A_n = A_m$. 
:::

Here's another proof that may be more elegant, depending on who you ask.

::: {.proof}
Let $k \in \mathbb{N}$.
From lemma 2, there exists $m \in \mathbb{N}$ such that $|A_m| \leq |A_n|$ for all $n \in \mathbb{N}$.
It follows that $|A_m| \leq |A_{m + k}|$. 
Furthermore, the definition of $A_n$ implies that $A_{m} \supseteq A_{m + k}$ and it follows that $|A_m| \geq |A_{m + k}|$ as $A_m$ and $A_{m+k}$ are finite sets. 
With $|A_m| \leq |A_{m + k}|$ and $|A_m| \geq |A_{m + k}|$, the only possibility is that $|A_m| = |A_{m+k}|$ and consequently $A_m = A_{m + k}$.
Finally, it follows that
$$
\begin{align*}
    \bigcap_{n=1}^{\infty}A_n &= (\bigcap_{n=1}^{m}A_n) \cap (\bigcap_{n=m+1}^{\infty}A_n) \\
    &= A_m \cap (\bigcap_{n=m+1}^{\infty}A_m) \\
    &= A_m \cap A_m \\
    &= A_m
\end{align*}
$$
Therefore we have that $\bigcap_{n=1}^{\infty}A_n = A_m$ as desired.
:::
:::

Since $A_m$ is finite and nonempty, it follows that (b) is a *true* statement.

### (c)

It is a widely known mathematical fact that the set operations are also distributive, i.e.,
$$
A \cap (B \cup C) = (A \cap B) \cup (A \cap C)
$$
[Therefore, (e) is a true statement, which we will later prove.]

Therefore, if $A \cap (B \cup C) = (A \cap B) \cup C$, then $A \cap C = C$.
Since $A \cap C = C$ if and only if $C \subseteq A$, it follows that (c) is a true statement if and only if $C \subseteq A$. 
Any set $C$ that is not a subset of $A$ should then invalidate the equality.

For counterexample, let $A, B, C$ be sets with
$$
\begin{align*}
    A &= \{a\} \\
    B &= \{b\} \\
    C &= \{c\}
\end{align*}
$$

It follows that $A \cap (B \cup C) = \{a\} \cap \{b, c\} = \emptyset$, but $(A \cap B) \cup C = \emptyset \cup \{c\} = \{c\}$, thus $A \cap (B \cup C) \not = (A \cap B) \cup C$.
Hence, (c) is a *false* statement.

### (d)

It also is a widely known mathematical fact that set operations are associative.
Set operation associativity is derived from the associativity of the logical connectives.

::: {#lem-order}
Let $A, B, C$ be sets. Then, $A \cap (B \cap C) = (A \cap B) \cap C$.

::: {.proof}
Let $x \in A \cap (B \cap C)$.
We have that $x \in A$ and $x \in B \cap C$, and it follows that $x \in B$ and $x \in C$. 
With $x \in A$ and $x \in B$, it follows that $x \in A \cap B$, and consequently $x \in (A \cap B) \cap C$ and we have that $A \cap (B \cap C) \subseteq (A \cap B) \cap C$.

Now, let $x \in (A \cap B) \cap C$.
Similarly, we have that $x \in A \cap B$ and $x \in C$, and it follows that $x \in A$ and $x \in B$.
Thus, $x \in B \cap C$ and consequently $x \in A \cap (B \cap C)$.
With $A \cap (B \cap C) \supseteq (A \cap B) \cap C$, it follows that $A \cap (B \cap C) = (A \cap B) \cap C$ as desired.
:::
:::

With Lemma 4, it follows that (d) is a *true* statement. 

### (e)

Now let us prove the distributive property mentioned in (c).
Similar to (d), the distributive property for logical connectives implies the distributive property for the set opertations.

::: {#lem-order}
Let $A, B, C$ be sets. Then, $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$.

::: {.proof}
Let $x \in A \cap (B \cup C)$. We have that $x \in A$ and $x \in B \cup C$, and it follows that $x \in B$ or $x \in C$. 
Hence, we have that $(x \in A$  and $x \in B)$ or $(x \in A$ and $x \in C)$, and it follows that $x \in A \cap B$ or $x \in A \cap C$, thus $x \in (A \cap B) \cup (A \cap C)$.
Consequently, $A \cap (B \cup C) \subseteq (A \cap B) \cup (A \cap C)$. 

Let $x \in (A \cap B) \cup (A \cap C)$.
Then, $x \in A \cap B$ or $x \in A \cap C$, and it follows that $(x \in A$ and $x \in B)$ or $(x \in A$ and $x \in C)$. 
Distributive property for logical connectives implies that $x \in A$ and $(x \in B$ or $x \in C)$, and we have that $x \in A$ and $x \in B \cup C$. With $x \in A \cap (B \cup C)$, it follows that $A \cap (B \cup C) \supseteq (A \cap B) \cup (A \cap C)$, and we conclude that $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$ as desired.
:::
:::