---
title: "Exercise 1.2.6"
---

## Problem

(a) Verify the triangle inequality in the special case where $a$ and $b$ have the same sign.
(b) Find an efficient proof for all the cases at once by first demonstrating $(a + b)^2 \leq (|a| + |b|)^2$.
(c) Prove $|a - b| \leq |a - c| + |c - d| + |d - b|$ for all $a, b, c,$ and $d$.
(d) Prove $||a| - |b|| \leq |a - b|$. (The unremarkable identity $a = a - b + b$ may be useful.)

## Solution

### (a)

::: {#lem-order}
Let $a, b \in \mathbb{R}$. If $a$ and $b$ have the same sign, then $|a + b| = |a| + |b|$. 

::: {.proof}
Suppose that $a = 0$ and $b = 0$.
It immediately follows that $|a + b| = |a| + |b| = 0$.

Suppose that $a > 0$ and $b > 0$.
With $a = |a|$ and $b = |b|$, we have that $a + b = |a| + |b|$. 
Since $a + b > 0$, we have that $a + b = |a + b|$, and thus $|a + b| = |a| + |b|$. 

Suppose that $a < 0$ and $b < 0$. 
With $-a = |a|$ and $-b = |b|$, we have that $(-a) + (-b) = |a| + |b|$.
Since $a + b < 0$, we have that $-(a + b) = |a + b|$, where $-(a + b) = (-a) + (-b)$. 
Thus it follows that $|a + b| = |a| + |b|$. 

In either case, we have that $|a + b| = |a| + |b|$. 
:::
:::

It then follows that $|a + b| \leq |a| + |b|$ for this particular case.

### (b)

::: {#lem-order}
Let $a, b \in \mathbb{R}$. Then, $(a + b)^2 \leq (|a| + |b|)^2$. 

::: {.proof}
With $a \leq |a|$ and $b \leq |b|$, we have that $ab \leq |a||b|$.
Furthermore, with $a^2 = |a|^2$ and $b^2 = |b|^2$, we have that $a^2 + 2ab + b^2 \leq |a|^2 + 2|a||b| + |b|^2$.
It then follows that $(a + b)^2 \leq (|a| + |b|)^2$.
:::
:::

While it is tempting to just take square roots call it a day, let us be slightly more rigorous and check that it is even possible to do so.

::: {#lem-order}
Let $x, y \in \mathbb{R}$.
If $x^2 \leq y^2$, then $|x| \leq |y|$. 

::: {.proof}
Suppose that $x^2 \leq y^2$.
It follows that $y^2 - x^2 = (y - x)(y + x) \geq 0$.
Since the product of $y-x$ and $y+x$ is nonnegative, either both factors are nonnegative or both factors are nonpositive.

Suppose that $y - x \geq 0$ and $y + x \geq 0$.
It follows that $x \leq y$ and $-x \leq y$, thus $|x| \leq y$.
With $y \leq |y|$, we have that $|x| \leq |y|$.

Suppose that $y - x \leq 0$ and $y + x \leq 0$.
It follows that $-x \leq -y$ and $x \leq -y$, thus $|x| \leq -y$. 
With $-y \leq |y|$, it follows that $|x| \leq |y|$.

In either case, it follows that $|x| \leq |y|$.
:::
:::

Combination of Lemma 2 and Lemma 3 make triangle inequality more of a corollary.

### (c)

::: {#lem-order}
Let $a, b, c, d \in \mathbb{R}$.
Then, $|a - b| \leq |a - c| + |c - d| + |d - b|$.

::: {.proof}
Notice that
$$
\begin{align*}
a - b &= a + (-c + c) + (-d + d) - b \\
&= (a - c) + (c - d) + (d - b)
\end{align*}
$$
Thus, $|a - b| \leq |a - c| + |(c - d) + (d - b)|$ by the triangle inequality, and another application yields $|a - b| \leq |a - c| + |c - d| + |d - b|$ as desired.
:::
:::

### (d) 

::: {#lem-order}
Let $a, b \in \mathbb{R}$.
Then, $||a| - |b|| \leq |a - b|$.

::: {.proof}
Notice that $a = a + (-b + b) = (a - b) + b$.
By the triangle inequality, we have that $|a| = |(a - b) + b| \leq |a - b| + |b|$.
It follows that $|a| - |b| \leq |a - b|$.

Suppose that $|a| - |b| \geq 0$.
Then, $||a|-|b|| = |a| - |b| \leq |a - b|$.

Suppose that $|a| - |b| < 0$. 
It follows that $|a| - |b| < 0 \leq |a - b|$.
We then have that $-|a - b| < |b| - |a|$, where $|a - b| = |b - a|$.
Thus, $-|b - a| < |b| - |a|$, (to be continued...)
:::
