---
title: "Exercise 1.2.4"
---

## Problem

Produce an infinite collection of sets $A_1, A_2, A_3, \ldots$ with the property that every $A_i$ has an infinite number of elements, $A_i \cap A_j = \emptyset$ for all $i \not = j$, and $\bigcup_{i=1}^{\infty} A_i = \mathbb{N}$.

## Solution

I think it is very helpful to state the Fundamental Theorem of Arithmetic, which is the core idea for this solution.
We can exploit the uniquessness of prime factorization to form the partitions of $\mathbb{N}$. 

::: {.lemma}
**Fundamental Theorem of Arithmetic** Let $n \in \mathbb{N}$ with $n > 1$.
Then there exist distinct primes $p_1 < p_2 < \ldots < p_k$ and $r_1,r_2,\ldots,r_k \in \mathbb{N}$
such that
$$
n = \prod_{i=1}^k p_i^{r_i}
$$
Moreover, this factorization is unique up to the ordering of the primes.
:::

Furthermore, we will also need to rely on the infinitude of primes to make our partitioned sets infinite.

::: {.lemma}
**Euclid's Theorem** There exist infinitely many primes.
:::

Let us form partitions of $\mathbb{N}$ by grouping natural numbers with the same number of prime factors including multiplicity.

Let $A_1 = \{1\} \cup \{p_1, p_2, \ldots\} = \{1, p_1, p_2, \ldots\}$ and for $i > 1$, let $A_i \subset \mathbb{N}$ such that
$$
A_i = \{n \in \mathbb{N} : n = \prod_{j=1}^k p_j^{r_j} \text{ and } \sum_{j = 1}^{k} r_j = i\}
$$

Let us prove the following lemmas to formalize our solution.

::: {#lem-order}
For all $i \in \mathbb{N}$, $A_i$ is infinite.

::: {.proof}
Let $i \in \mathbb{N}$, and let $P_i = \{ p_j^i : j \in \mathbb{N}\}$.
Consider the following cases.

Suppose that $i = 1$.
It follows that $A_1 = \{1\} \cup P_1$, and since $P_1$ is infinite by Euclid's Theorem, it follows that $A_1$ is infinite with $P_1 \subseteq A_1$.

Suppose that $i > 1$, and let $n \in P_i$.
It follows that there exists $j \in \mathbb{N}$ such that $n = p_j^i$. 
Since the prime factorization of $n$ has $i$ prime factors, it follows that $n \in A_i$, and thus $P_i \subseteq A_i$.
$P_i$ is also infinite by Euclid's Theorem, so it follows that $A_i$ is infinite as well.

In either case, $A_i$ is infinite as desired.
:::
:::

In particular, notice that $A_j$ is nonempty - this is a requirement for $A_i$ to be a partition of $\mathbb{N}$.

::: {#lem-order}
For all $i, j \in \mathbb{N}$, if $i \not = j$, then $A_i \cap A_j = \emptyset$.

::: {.proof}
Let $i, j \in \mathbb{N}$ and suppose that $i \not = j$.
For the sake of contradiction, suppose that $A_i \cap A_j \not = \emptyset$.
Let $n \in A_i \cap A_j$. It follows that $n \in A_i$ and $n \in A_j$, thus $n$ has $i$ prime factors and $j$ prime factors.
However, this is a contradiction as the fundamental theorem of arithmetic as the prime factorzation of $n$ is no longer unique. 
Therefore, $n$ does not exist, and it follows that $A_i \cap A_j = \emptyset$. 
:::
:::

::: {#lem-order}
$\bigcup_{i=1}^{\infty} A_i = \mathbb{N}$

::: {.proof}
Let $n \in \bigcup_{i=1}^{\infty} A_i$.
It follows that there exists $i \in \mathbb{N}$ with $n \in A_i$.
Since $A_i \subseteq \mathbb{N}$, it follows that $n \in \mathbb{N}$.
Therefore, $\bigcup_{i=1}^{\infty} A_i \subseteq \mathbb{N}$.

Let $n \in \mathbb{N}$.
By the fundamental theorem of arithmetic, there exist primes $p_1, p_2, \ldots, p_k$ and $r_1, r_2, \ldots, r_k \in \mathbb{N}$ such that
$$
n = \prod_{i=1}^{k} p_i^{r_i}
$$
and let $K = \sum_{i=1}^{k} r_i$.
It follows that $n \in A_K$ and with $A_K \subseteq \bigcup_{i=1}^{\infty} A_i$, we have that $n \in \bigcup_{i=1}^{\infty} A_i$. 
Thus, $\mathbb{N} \subseteq \bigcup_{i=1}^{\infty} A_i$ and we conclude that $\bigcup_{i=1}^{\infty} A_i = \mathbb{N}$.
:::
:::
By lemmas 1, 2, and 3, it follows that $A_i$ forms a partition of $\mathbb{N}$.